name: StackCalc32
options:
  bundleIdPrefix: rpn.calculator
targets:
  StackCalc32Container:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - StackCalc32Container
      - StackCalc32-iOS
      - Shared
      - StackCalc32/Views/Plotting
      - StackCalc32/Views/Menus
      - StackCalc32/Views/Equations
      - StackCalc32/Views/IntegratePromptView.swift
      - StackCalc32/Views/SolvePromptView.swift
      - StackCalc32/Views/Styles
    settings:
      SKIP_INSTALL: NO
      PRODUCT_BUNDLE_IDENTIFIER: "rpn.calculator.WatchCalc32"
      DEVELOPMENT_TEAM: "UNXVA46694"
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: StackCalc32Container/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: RPNCore
      - target: StackCalc32
        embed: true

  StackCalc32:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources: [StackCalc32, Shared]
    settings:
      SKIP_INSTALL: YES
      DEVELOPMENT_TEAM: UNXVA46694
      CODE_SIGN_STYLE: Automatic
      PRODUCT_BUNDLE_IDENTIFIER: rpn.calculator.WatchCalc32.watchkitapp
      INFOPLIST_FILE: StackCalc32/Info.plist
      SWIFT_VERSION: "5.9"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: RPNCore

  StackCalc32UITests:
    type: bundle.ui-testing
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - StackCalc32UITests
      - fastlane/SnapshotHelper.swift
      - RPNCore/Tests/RPNCoreTests/SharedCalculatorTest.swift
      - RPNCore/Tests/RPNCoreTests/SharedCalculatorThoroughTestCases.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: rpn.calculator.WatchCalc32UITests
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: StackCalc32
      - package: RPNCore

  StackCalc32ContainerUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - StackCalc32UITests
      - fastlane/SnapshotHelper.swift
      - RPNCore/Tests/RPNCoreTests/SharedCalculatorTest.swift
      - RPNCore/Tests/RPNCoreTests/SharedCalculatorThoroughTestCases.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: rpn.calculator.WatchCalc32ContainerUITests
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: StackCalc32Container
      - package: RPNCore

schemes:
  StackCalc32Container:
    build:
      targets:
        StackCalc32Container: all
    test:
      targets:
        - StackCalc32ContainerUITests

  StackCalc32:
    build:
      targets:
        StackCalc32: all
    test:
      targets:
        - StackCalc32UITests

packages:
  RPNCore:
    path: RPNCore
