name: WatchCalc32
options:
  bundleIdPrefix: rpn.calculator
targets:
  WatchCalc32Container:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - WatchCalc32Container
      - WatchCalc32-iOS
      - Shared
      - WatchCalc32/Views/Plotting
      - WatchCalc32/Views/Menus
      - WatchCalc32/Views/Equations
      - WatchCalc32/Views/IntegratePromptView.swift
      - WatchCalc32/Views/SolvePromptView.swift
      - WatchCalc32/Views/Styles
    settings:
      SKIP_INSTALL: NO
      PRODUCT_BUNDLE_IDENTIFIER: "rpn.calculator.WatchCalc32"
      DEVELOPMENT_TEAM: "UNXVA46694"
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: WatchCalc32Container/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: RPNCore
      - target: WatchCalc32
        embed: true

  WatchCalc32:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources: [WatchCalc32, Shared]
    settings:
      SKIP_INSTALL: YES
      DEVELOPMENT_TEAM: UNXVA46694
      CODE_SIGN_STYLE: Automatic
      PRODUCT_BUNDLE_IDENTIFIER: rpn.calculator.WatchCalc32.watchkitapp
      INFOPLIST_FILE: WatchCalc32/Info.plist
      SWIFT_VERSION: "5.9"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: RPNCore

  WatchCalc32UITests:
    type: bundle.ui-testing
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - WatchCalc32UITests
      - fastlane/SnapshotHelper.swift
      - RPNCore/Tests/RPNCoreTests/SharedCalculatorTest.swift
      - RPNCore/Tests/RPNCoreTests/SharedCalculatorThoroughTestCases.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: rpn.calculator.WatchCalc32UITests
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: WatchCalc32
      - package: RPNCore

  WatchCalc32ContainerUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - WatchCalc32ContainerUITests
      - fastlane/SnapshotHelper.swift
      - RPNCore/Tests/RPNCoreTests/SharedCalculatorTest.swift
      - RPNCore/Tests/RPNCoreTests/SharedCalculatorThoroughTestCases.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: rpn.calculator.WatchCalc32ContainerUITests
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: WatchCalc32Container
      - package: RPNCore

schemes:
  WatchCalc32Container:
    build:
      targets:
        WatchCalc32Container: all
    test:
      targets:
        - WatchCalc32ContainerUITests

  WatchCalc32:
    build:
      targets:
        WatchCalc32: all
    test:
      targets:
        - WatchCalc32UITests

packages:
  RPNCore:
    path: RPNCore
