import Foundation
import AppKit
import CoreGraphics
import CoreText

let saveDir = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "."

// Sizes matches generate_font.py
struct FontSizeConfig {
    let name: String
    let height: Int
    let bytesPerRow: Int
}

let sizes: [FontSizeConfig] = [
    FontSizeConfig(name: "Tiny", height: 10, bytesPerRow: 1),
    FontSizeConfig(name: "Small", height: 12, bytesPerRow: 1),
    FontSizeConfig(name: "Display", height: 16, bytesPerRow: 2),
    FontSizeConfig(name: "Medium", height: 20, bytesPerRow: 2),
    FontSizeConfig(name: "Large", height: 32, bytesPerRow: 3)
]

let specialChars: [String: UInt32] = [
    "√": 8730,
    "ʸ": 739, // y superscript?
    "ˣ": 738, // x superscript?
    "Σ": 931,
    "π": 960,
    "θ": 952,
    "°": 176,
    "▶": 9656,
    "∫": 8747,
    "̄": 772,
    "σ": 963,
    "▼": 9660,
    "⚙": 9881,
    "e": 119890,
    "x": 119909,
    "²": 178,
    "y": 119910,
    "↔": 8596
]

var allChars: [String: UInt32] = [:]
for i in 32...126 {
    allChars[String(UnicodeScalar(UInt8(i)))] = UInt32(i)
}
for (k, v) in specialChars {
    allChars[k] = v
}

// Map some of the string to correct SF symbols if standard character doesn't render perfectly
// e.g. "e", "x", "y" mathematically. We'll just draw them as the actual text for now, using the system font.

var fileContent = "// Automatically generated by FontExporter (San Francisco native)\n"
fileContent += "public struct FontData {\n"

for config in sizes {
    print("Generating \(config.name)...")
    let font = NSFont.systemFont(ofSize: CGFloat(config.height - 2), weight: .medium)
    
    fileContent += "    public struct \(config.name) {\n"
    fileContent += "        public static let charHeight: Int = \(config.height)\n"
    fileContent += "        public static let bytesPerRow: Int = \(config.bytesPerRow)\n\n"
    
    var offset = 0
    var bitmapDataContent = "        public static let bitmapData: [UInt8] = [\n            "
    var glyphCases = ""
    
    for (charString, code) in allChars.sorted(by: { $0.value < $1.value }) {
        let attrStr = NSAttributedString(string: charString, attributes: [.font: font, .foregroundColor: NSColor.white])
        let size = attrStr.size()
        let width = charString == " " ? Int(size.width) : max(Int(ceil(size.width)), 1)
        
        let bitmapWidth = max(width, 1)
        let bitmapHeight = config.height
        
        let colorSpace = CGColorSpaceCreateDeviceGray()
        let rawData = UnsafeMutablePointer<UInt8>.allocate(capacity: bitmapWidth * bitmapHeight)
        rawData.initialize(repeating: 0, count: bitmapWidth * bitmapHeight)
        
        if let context = CGContext(data: rawData,
                                   width: bitmapWidth,
                                   height: bitmapHeight,
                                   bitsPerComponent: 8,
                                   bytesPerRow: bitmapWidth,
                                   space: colorSpace,
                                   bitmapInfo: CGImageAlphaInfo.none.rawValue) {
            
            let graphicsContext = NSGraphicsContext(cgContext: context, flipped: false)
            NSGraphicsContext.saveGraphicsState()
            NSGraphicsContext.current = graphicsContext
            
            let yOffset = (CGFloat(bitmapHeight) - (font.ascender - font.descender)) / 2.0 - font.descender
            attrStr.draw(at: NSPoint(x: 0, y: yOffset))
            NSGraphicsContext.restoreGraphicsState()
            
            var bitmapArray: [UInt8] = []
            for y in 0..<bitmapHeight {
                for byteIdx in 0..<config.bytesPerRow {
                    var byteVal: UInt8 = 0
                    for bitIdx in 0..<8 {
                        let x = byteIdx * 8 + bitIdx
                        if x < bitmapWidth {
                            let flippedY = bitmapHeight - 1 - y
                            let pixelVal = rawData[flippedY * bitmapWidth + x]
                            if pixelVal > 127 {
                                byteVal |= (1 << (7 - bitIdx))
                            }
                        }
                    }
                    bitmapArray.append(byteVal)
                }
            }
            
            let hexBitmap = bitmapArray.map { String(format: "0x%02X", $0) }.joined(separator: ", ")
            bitmapDataContent += hexBitmap + ",\n            "
            
            glyphCases += "            case \(code): return (width: \(width), offset: \(offset))\n"
            offset += bitmapArray.count
        }
        rawData.deallocate()
    }
    
    bitmapDataContent += "0x00\n        ]\n\n"
    fileContent += bitmapDataContent
    
    fileContent += "        public static func glyph(forScalar scalar: UInt32) -> (width: Int, offset: Int)? {\n"
    fileContent += "            switch scalar {\n"
    fileContent += glyphCases
    fileContent += "            default: return nil\n"
    fileContent += "            }\n"
    fileContent += "        }\n"
    fileContent += "    }\n\n"
}

fileContent += "}\n"

let url = URL(fileURLWithPath: saveDir).appendingPathComponent("FontData.swift")
try! fileContent.write(to: url, atomically: true, encoding: .utf8)
print("Saved FontData.swift to \(url.path)")
