public enum CalculatorOperation: Int, CaseIterable, Equatable, Hashable {
    case toCm = 1
    case toGal = 2
    case toIn = 3
    case toKg = 4
    case toKm = 5
    case toLiters = 6
    case toLb = 7
    case toMi = 8
    case toCelsius = 9
    case toFahrenheit = 10
    
    case digit0 = 11
    case digit1 = 12
    case digit2 = 13
    case digit3 = 14
    case digit4 = 15
    case digit5 = 16
    case digit6 = 17
    case digit7 = 18
    case digit8 = 19
    case digit9 = 20
    
    case add = 21
    case subtract = 22
    case multiply = 23
    case divide = 24
    case decimal = 25
    case enter = 26
    case toggleSign = 27
    
    case reciprocal = 28
    case exp10 = 29
    case exp = 30
    case power = 31
    case xRootY = 32
    case square = 33
    case sqrt = 34
    case factorial = 35
    
    case toDeg = 36
    case toHms = 37
    case toHr = 38
    case toRad = 39
    case toRectangular = 40
    case toPolar = 41
    
    case abs = 42
    case acos = 43
    case and = 44
    case asin = 45
    case atan = 46
    case backspace = 47
    case base = 48
    case bin = 49
    case c = 50
    case clear = 51
    case cmplx = 52
    case const = 53
    case cos = 54
    case dec = 55
    case disp = 56
    case e = 57
    case eng = 58
    case eqn = 59
    case fix = 60
    case flags = 61
    case fnEq = 62
    case frac = 63
    case gto = 64
    case hex = 65
    case hyp = 66
    case intg = 67
    case intDiv = 68
    case lr = 69
    case lastx = 70
    case lbl = 71
    case lfu0 = 72
    case lfu1 = 73
    case lfu2 = 74
    case lfu3 = 75
    case lfu4 = 76
    case lfu5 = 77
    case ln = 78
    case log = 79
    case mem = 80
    case modes = 81
    case not = 82
    case oct = 83
    case off = 84
    case or = 85
    case parts = 86
    case plot = 87
    case _prgm = 88
    case prob = 89
    case nPr = 135
    case nCr = 136
    case rand = 137
    case rcl = 90
    case regs = 91
    case rnd = 92
    case modulo = 132
    case rtn = 133
    case scrl = 134
    case rollUp = 93
    case rollDown = 94
    case sci = 95
    case setExam = 96
    case setStack = 97
    case show = 98
    case sin = 99
    case solve = 100
    case sto = 101
    case sums = 102
    case tan = 103
    case view = 104
    case xeq = 105
    case xor = 106
    
    case statStdDev = 107
    case statMean = 108
    case statAdd = 109
    case statSub = 110
    
    case testNeq0 = 111
    case testNeq = 112
    case testLt0 = 113
    case testLte0 = 114
    case testLte = 115
    case testLt = 116
    case testEq0 = 117
    case testEq = 118
    case testGt0 = 119
    case testGt = 120
    
    case testX0 = 121
    case testXY = 122
    
    case swapXYPrompt = 123
    case swapXY = 124
    
    case integrate = 125
    
    case percent = 126
    case percentChange = 127
    case pi = 128
    
    case scrollUp = 138
    case scrollDown = 139
    case fdisp = 140
    case slashc = 141
    
    // Shift modifier keys sent directly
    case shiftYellow = 129
    case shiftBlue = 130

    public var stringValue: String {
        switch self {
        case .toCm: return "→cm"
        case .toGal: return "→gal"
        case .toIn: return "→in"
        case .toKg: return "→kg"
        case .toKm: return "→km"
        case .toLiters: return "→l"
        case .toLb: return "→lb"
        case .toMi: return "→mi"
        case .toCelsius: return "→°C"
        case .toFahrenheit: return "→°F"
        case .digit0: return "0"
        case .digit1: return "1"
        case .digit2: return "2"
        case .digit3: return "3"
        case .digit4: return "4"
        case .digit5: return "5"
        case .digit6: return "6"
        case .digit7: return "7"
        case .digit8: return "8"
        case .digit9: return "9"
        case .add: return "+"
        case .subtract: return "-"
        case .multiply: return "×"
        case .divide: return "÷"
        case .decimal: return "."
        case .enter: return "ENTER"
        case .toggleSign: return "+/-"
        case .reciprocal: return "1/𝑥"
        case .exp10: return "10ˣ"
        case .exp: return "𝑒ˣ"
        case .power: return "𝑦ˣ"
        case .xRootY: return "xVy"
        case .square: return "𝑥²"
        case .sqrt: return "√𝑥"
        case .factorial: return "𝑥!"
        case .toDeg: return ">DEG"
        case .toHms: return ">HMS"
        case .toHr: return ">HR"
        case .toRad: return ">RAD"
        case .toRectangular: return ">y,x"
        case .toPolar: return ">θ,r"
        case .abs: return "ABS"
        case .acos: return "ACOS"
        case .and: return "AND"
        case .asin: return "ASIN"
        case .atan: return "ATAN"
        case .backspace: return "←"
        case .base: return "BASE"
        case .bin: return "BIN"
        case .c: return "C"
        case .clear: return "CLEAR"
        case .cmplx: return "CMPLX"
        case .const: return "CONST"
        case .cos: return "COS"
        case .dec: return "DEC"
        case .disp: return "DISP"
        case .e: return "E"
        case .eng: return "ENG"
        case .eqn: return "EQN"
        case .fix: return "FIX"
        case .flags: return "FLAGS"
        case .fnEq: return "FN="
        case .frac: return "FRAC"
        case .gto: return "GTO"
        case .hex: return "HEX"
        case .hyp: return "HYP"
        case .intg: return "INTG"
        case .intDiv: return "INT÷"
        case .lr: return "L.R."
        case .lastx: return "LAST𝑥"
        case .lbl: return "LBL"
        case .lfu0: return "LFU_0"
        case .lfu1: return "LFU_1"
        case .lfu2: return "LFU_2"
        case .lfu3: return "LFU_3"
        case .lfu4: return "LFU_4"
        case .lfu5: return "LFU_5"
        case .ln: return "LN"
        case .log: return "LOG"
        case .mem: return "MEM"
        case .modes: return "MODES"
        case .not: return "NOT"
        case .oct: return "OCT"
        case .off: return "OFF"
        case .or: return "OR"
        case .parts: return "PARTS"
        case .plot: return "PLOT"
        case ._prgm: return "PRGM"
        case .prob: return "PROB"
        case .nPr: return "nPr"
        case .nCr: return "nCr"
        case .rand: return "RAND"
        case .rcl: return "RCL"
        case .regs: return "REGS"
        case .rnd: return "RND"
        case .rollUp: return "R↑"
        case .rollDown: return "R↓"
        case .sci: return "SCI"
        case .setExam: return "SET_EXAM"
        case .setStack: return "SET_STACK"
        case .show: return "SHOW"
        case .sin: return "SIN"
        case .solve: return "SOLVE"
        case .sto: return "STO"
        case .sums: return "SUMS"
        case .tan: return "TAN"
        case .view: return "VIEW"
        case .xeq: return "XEQ"
        case .xor: return "XOR"
        case .statStdDev: return "s,σ"
        case .statMean: return "𝑥̄,𝑦̄"
        case .statAdd: return "Σ+"
        case .statSub: return "Σ-"
        case .testNeq0: return "x!=0"
        case .testNeq: return "x!=y"
        case .testLt0: return "x<0"
        case .testLte0: return "x<=0"
        case .testLte: return "x<=y"
        case .testLt: return "x<y"
        case .testEq0: return "x=0"
        case .testEq: return "x=y"
        case .testGt0: return "x>0"
        case .testGt: return "x>y"
        case .testX0: return "𝑥?0"
        case .testXY: return "𝑥?𝑦"
        case .swapXYPrompt: return "x↔?"
        case .swapXY: return "x↔y"
        case .integrate: return "∫FN"
        case .percent: return "%"
        case .percentChange: return "%CHG"
        case .modulo: return "MOD"
        case .rtn: return "RTN"
        case .scrl: return "SCRL"
        case .pi: return "π"
        case .shiftYellow: return "SHIFT_YELLOW"
        case .shiftBlue: return "SHIFT_BLUE"
        case .fdisp: return "FDISP"
        case .slashc: return "/c"
        case .scrollUp: return "↑"
        case .scrollDown: return "↓"
        }
    }
    public var alphaLabel: String? {
        switch self {
        case .sqrt: return "A"
        case .exp: return "B"
        case .ln: return "C"
        case .power: return "D"
        case .reciprocal: return "E"
        case .statAdd: return "F"
        case .sto: return "G"
        case .rcl: return "H"
        case .rollDown: return "I"
        case .sin: return "J"
        case .cos: return "K"
        case .tan: return "L"
        case .enter: return "M"
        case .swapXY: return "N"
        case .toggleSign: return "O"
        case .e: return "P"
        case .digit7: return "Q"
        case .digit8: return "R"
        case .digit9: return "S"
        case .digit4: return "T"
        case .digit5: return "U"
        case .digit6: return "V"
        case .digit1: return "W"
        case .digit2: return "X"
        case .digit3: return "Y"
        case .digit0: return "Z"
        case .decimal: return "i"
        case .plot: return "(i)"
        default: return nil
        }
    }
}
